# Generated by Django 3.2.5 on 2021-07-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_rename_full_name_userprofile_default_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_phone_number',
            new_name='phone_number',
        ),
    ]
