# Generated by Django 3.2.5 on 2021-07-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=254)),
                ('sub_title_1', models.CharField(max_length=254)),
                ('main_title_2', models.CharField(max_length=254)),
                ('sub_title_3', models.CharField(max_length=254)),
            ],
        ),
    ]
