# Generated by Django 3.2.5 on 2021-07-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Work',
        ),
    ]
