# Generated by Django 3.2.5 on 2021-07-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_rename_trip_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='sub_title_3',
            new_name='sub_title_2',
        ),
    ]
