# Generated by Django 3.2.5 on 2021-07-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='city',
        ),
    ]
