# Generated by Django 3.0.4 on 2021-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('movie_quote', models.TextField(max_length=300)),
                ('paragraph_1', models.TextField(max_length=300)),
                ('paragraph_2', models.TextField(max_length=300)),
                ('paragraph_3', models.TextField(max_length=300)),
            ],
        ),
    ]
