# Generated by Django 3.0.4 on 2021-07-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
