# Generated by Django 3.2.5 on 2021-07-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
