# Generated by Django 3.2.5 on 2021-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('movie_quote', models.TextField(max_length=254)),
                ('p_1', models.TextField(max_length=254)),
                ('p_2', models.TextField(max_length=254)),
                ('p_3', models.TextField(max_length=254)),
            ],
        ),
    ]
